# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'moviesApp_viewCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  inherit! :search_paths
  use_frameworks!
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 6.0'
  pod 'RealmSwift'
 
  target 'moviesApp_viewCodeTests' do
    inherit! :search_paths
    use_frameworks!
    # Pods for testing
    pod 'iOSSnapshotTestCase'
  end

  target 'moviesApp_viewCodeUITests' do
    # Pods for testing
  end

end
